### ISSUE TITLE
how to modify this to adapt my project?

### ISSUE THREAD

**Issue by alexzhuke** [zzet/ansible-postgresql-role#13]
Hi,

I noticed this project can be used in my project which should deploy the postgresql on remote machine and configure it .

I'm the fresh man in Ansible area, at least not  too fresh to write ansible-playbooks. How could I reuse your playbook on my project? I means change simple configurations or parameters.

**Comment by zzet** [comment]
Hi. You can override any configuration params from https://github.com/zzet/ansible-postgresql-role/blob/master/defaults/main.yml

``` bash
$ ansible-galaxy install zzet.postgresql
```

```yaml
- hosts: db
  vars:
    # here you can override some params
    # ex
    pg_version: 9.4
  roles:
    - role: zzet.postgresql
      # here you can also override params
```
